version: '3.4'

services:
  expensestrackbot:
    image: expensestrackbot
    build:
      context: ./..
      dockerfile: ./Docker/Dockerfile
    command: [ "python", "main.py", "--log=DEBUG" ]
    environment:
      - BOT_TOKEN
