version: '3.4'

services:
  db:
    image: postgres:alpine3.18
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db-data-tests:/var/lib/postgresql/data/pgdata
      - ../db-scripts:/docker-entrypoint-initdb.d
  test:
    image: expensestrackbot
    build:
      context: ./..
      dockerfile: ./Docker/Dockerfile
    command: [ "python", "tests/test_db.py", "-v" ]
    environment:
      - BOT_TOKEN
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    depends_on:
      - db

volumes:
  db-data-tests:
