name: Build Docker Image

on:
  push:
    branches:
      - main

  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repository
      uses: actions/checkout@v2

    - name: Build Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Docker/Dockerfile
        push: false
        tags: expensestrackerbot:latest

    - name: Save Image
      run: |
        docker save expensestrackerbot:latest | gzip > /tmp/expensestrackerbot.tgz

    - name: Run docker-compose build
      run: docker-compose -f Docker/docker-compose.test.yml build

    - name: Run docker-compose test
      run: docker-compose -f Docker/docker-compose.test.yml run test

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: expensestrackerbot
        path: /tmp/expensestrackerbot.tgz

