name: Build Docker Image

on:
  push:
    branches:
      - main  # Adjust the branch name if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repository
      uses: actions/checkout@v2

    - name: Build Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Docker/Dockerfile
        push: false
        tags: expensestrackerbot:latest
        outputs: type=docker,dest=/tmp/myimage.tar

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: myimage
        path: /tmp/myimage.tar
